### ISSUE TITLE
Commenting is not working

### ISSUE THREAD

**Issue by Davidek577** [nickpettican/InstaBot#1]
Commenting is not working for me, even on the default configuration.
I get the message:
`Error: while commenting - debugging needed.`
Please help

**Comment by nickpettican** [comment]
I just spotted it too, it's a unicode error when adding the comment to the log. 

I'll try and fix it ASAP but I'm on holiday until Tuesday. Leave comments off for now, or 'comment out' (#) `self.console_log(comment + '\,')` in `explore_operation` and see if that works.

**Comment by Davidek577** [comment]
It works! Thank you very much. But there is yet one another issue - it comment the same photo multiple times.

**Comment by nickpettican** [comment]
Hmm that shouldn't be happening. Does it do it repeatedly during the operation?
