### ISSUE TITLE
ImportError: No module named Arrow

### ISSUE THREAD

**Issue by alexsonnay** [nickpettican/InstaBot#10]
I get this error when trying to run the run "run.py".

I did install Arrow though...
"Successfully installed Arrow-0.10.0 python-dateutil-2.6.0"

any ideas ?

Thx

**Comment by nickpettican** [comment]
Strange... here are some things to check:
- [ ] Are you using Python 2.7
- [ ] Did you run `pip install arrow` with lowercase
- [ ] Is `arrow` lowercase throughout

Other than that I'm not sure. That error message should be `No module named arrow` not `Arrow`
