### ISSUE TITLE
Error backing up when commenting with emojis

### ISSUE THREAD

**Issue by newsum** [nickpettican/InstaBot#19]
I'm getting this error after I commented using an emoji. Looks like the script can't save to the activity log maybe?

Error backing up: 'ascii' codec can't encode character u'\U0001f60d' in position 89: ordinal not in range(128)

**Comment by nickpettican** [comment]
Hi @newsum, thanks again for the feedback. Yes it appears so, I'll change the log file to `.txt` instead to see if that removes the issue. 
Download the latest version and let me know if it works!

**Comment by nickpettican** [comment]
I'm guessing it works now, so I'm closing the issue.
Feel free to reopen if the problem subsists!
