### ISSUE TITLE
instabot not sign in

### ISSUE THREAD

**Issue by oilujc** [nickpettican/InstaBot#20]
Hello friends, I have been trying to use Instabot but at the moment of initiating it appears ERROR, could not sign in.
ERROR while attempting sign in
does not show me some other error more than those, I can add that the account if it really exists

**Comment by oilujc** [comment]
Hello, I have checked again and it still does not work, the only change to the script that I did in addition to the configuration data was to instafunctions.py when importing random because it gave me error.

 InstaBot V 1.2.0 by nickpettican
        Automate your Instagram activity

        New features:
        - Only unfollow who has not followed back
        - Added timestamps to log
        - Added customisable comments list to config

[ 2017-11-30 16:43:29 ] Trying to sign in as myuser...  ERROR, could not sign in.

ERROR while attempting sign in

Traceback (most recent call last):
  File "run.py", line 45, in <module>
    main()
  File "run.py", line 41, in main
    instabot = InstaBot(profile, data = data)
  File "C:\Users\jcmar\Desktop\Proyectos\Python\instbot\InstaBot-master\src\instabot.py", line 135, in __init__
    self.init_profile()
  File "C:\Users\jcmar\Desktop\Proyectos\Python\instbot\InstaBot-master\src\instabot.py", line 209, in init_profile
    self.profile.import_profile(check_user(self.browser, self.insta_urls['user'], self.params['username']))
  File "C:\Users\jcmar\Desktop\Proyectos\Python\instbot\InstaBot-master\src\instafunctions.py", line 181, in check_user
    sleep(5*random.random())
AttributeError: 'builtin_function_or_method' object has no attribute 'random'

this is the complete message when I try to log in after that

 InstaBot V 1.2.0 by nickpettican
        Automate your Instagram activity

        New features:
        - Only unfollow who has not followed back
        - Added timestamps to log
        - Added customisable comments list to config

[ 2017-11-30 16:44:04 ] Trying to sign in as myuser...  ERROR, could not sign in.

ERROR while attempting sign in


Starting operations - 16:44:13 30/11/2017

Current daily count:
 - All operations: 0
 - Like news feed: 0
 - Likes: 0
 - Follows: 0
 - Unfollows: 0
 - Comments: 0

Finishing operations...
        Waiting 35 seconds

Error while attempting logout

Thank you for using InstaBot!

**Comment by nickpettican** [comment]
Hi @oilujc great, glad you managed to sort it out. Thanks for finding that "random" bug, the latest commit should have fixed it 👍
