### ISSUE TITLE
Pip errors on Raspberry Pi

### ISSUE THREAD

**Issue by abhi21x** [nickpettican/InstaBot#22]
Thanks Nick for building the bot. The description page says that the bot should work on a raspberry Pi, but **while installing the requirements via pip**, I am getting the following error :

```
Could not find a version that satisfies the requirement time (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for time (from -r requirements.txt (line 3))
```

**Comment by nickpettican** [comment]
Hi @abhi21x thanks for the feedback.
Apologies for that, I was meant to fix this issue. Just remove `time` from the requirements.txt file.

**Comment by abhi21x** [comment]
Hi Nick. Thanks for your reply. I tried removing "Time" from requirements, then it started giving the same error for "random", when I removed "random" it started giving the same error for "operator" & so on.. Looks like arrow & requests are the only two not giving the error.

I am installing on Raspberry Pi 3. Maybe that could be the reason..

**Comment by andrewginns** [comment]
Try installing the requirements manually through pip. Syntax is:
pip install xxxxx

**Comment by abhi21x** [comment]
Manually installing through pip also gives the same error

```
Could not find a version that satisfies the requirement time (from versions: )
No matching distribution found for time
```

There could be packages missing for raspberry pi. I wanna know if anyone has made this work on a raspberry pi.

**Comment by andrewginns** [comment]
Time isn't needed to run the program on your pi. If everything else is installed try python run.py

**Comment by nickpettican** [comment]
I think time and random are default libraries so they should already be installed. To test it out go to your terminal and type:
```bash
python
> import time, random
```
If it doesn't through any errors they're installed.

Just so you know I think the bot is currently not working due to Instagram having changed their backend #21, I'll have it fixed soon though!

**Comment by abhi21x** [comment]
Running
```
python
> import arrow, requests, time, random, operator, json, itertools
```
did not give any error. Looks like they're already installed in Python 3.

**Comment by abhi21x** [comment]
Thanks, it's working now.

Only lxml wasn't installed, had to manually install it via

`sudo apt-get install python-lxml`

**Comment by nickpettican** [comment]
Sweet, yeah lxml is the only exception.

Oh but the bot runs on Python 2.7 @abhi21x 

Is it working?

**Comment by abhi21x** [comment]
Yes it's working. I think Raspbian comes pre-installed with Python 2.7 & Python 3.

**Comment by nickpettican** [comment]
I've also updated the bot to adjust to Instagram's update @abhi21x @andrewginns

**Comment by abhi21x** [comment]
Thanks Nick. Working great now 👌

**Comment by anonHan** [comment]
hlo, can someone help me solving some issues in my kali  machine. The "pip install instagram-py" command is giving a syntax error ie. invalid syntax.

**Comment by nickpettican** [comment]
You're in the wrong repo @anonHan, I think this is what you're looking for: https://github.com/deathsec/instagram-py and the solution is probably 
`sudo pip3 install instagram-py`
