### ISSUE TITLE
Getting errors: global name 'e' is not defined

### ISSUE THREAD

**Issue by eigentlichich** [nickpettican/InstaBot#23]
Bot stoped working a few days ago, did instagram changed something or ist it just the bot?

`Starting operations - 14:58:16 08/01/2018

Current daily count:
 - All operations: 1354
 - Like news feed: 11
 - Likes: 495
 - Follows: 424
 - Unfollows: 424
 - Comments: 0

[ 2018-01-08 14:58:19 ] Refilling bucket - looking for "starand" posts...  Error: global name 'e' is not defined. Trying again with glücklich...  Error: global name 'e' is not defined

Current daily count:
 - All operations: 1354
 - Like news feed: 11
 - Likes: 495
 - Follows: 424
 - Unfollows: 424
 - Comments: 0

[ 2018-01-08 14:58:25 ] Refilling bucket - looking for "streetmeetina" posts...  Error: global name 'e' is not defined. Trying again with meer...  Error: global name 'e' is not defined

Current daily count:
 - All operations: 1354
 - Like news feed: 11
 - Likes: 495
 - Follows: 424
 - Unfollows: 424
 - Comments: 0

[ 2018-01-08 14:58:32 ] Refilling bucket - looking for "dronestagram" posts...  Error: global name 'e' is not defined. Trying again with discoverearth...  Error: global name 'e' is not defined

Current daily count:
 - All operations: 1354
 - Like news feed: 11
 - Likes: 495
 - Follows: 424
 - Unfollows: 424
 - Comments: 0`

**Comment by nickpettican** [comment]
Hi @eigentlichich 
Thanks for the feedback. I think this issue was resolved, download the latest version.
However, this issue is directly correlated with #21 , I need to update the bot to reflect changes done to instagram's backend...

**Comment by nickpettican** [comment]
OK it should all work fine now 🙌
