### ISSUE TITLE
Error backing up: writelines() argument must be a sequence of strings

### ISSUE THREAD

**Issue by abhi21x** [nickpettican/InstaBot#25]
Hi Nick

There seems to be a new bug which comes up multiple times while running the script.

`Error backing up: writelines() argument must be a sequence of strings`

**Comment by nickpettican** [comment]
Hi @abhi21x , thanks for finding this bug, it may just be a matter of checking if the argument in the logger is an array and if not then wrap it up in one just before `writelines()`.

**Comment by nickpettican** [comment]
Fixed 👍
