### ISSUE TITLE
Error checking user: 'user'.

### ISSUE THREAD

**Issue by eliareutlinger** [nickpettican/InstaBot#27]
Is it just me or is there a problem with the user-verifying function `check_user()`?

![image](https://user-images.githubusercontent.com/14804153/37814858-97388c06-2e6c-11e8-8415-311a8fc8cf25.png)
![image](https://user-images.githubusercontent.com/14804153/37814883-ad8a5b2e-2e6c-11e8-9a1c-e72d79ce6a3d.png)

I tried to fix it myself but I can't find anything wrong. But since I'm a beginner, I don't really trust my skills.

**Comment by nickpettican** [comment]
Hi @eliareutlinger, thanks for the feedback. I think it's because Instagram changed their backend again, this is a keyError when extracting data from the Instagram API, thanks for finding it, I'll try and fix it ASAP :)

**Comment by eigentlichich** [comment]
@eliareutlinger same Problem here @nickpettican thanks for fixing

**Comment by nickpettican** [comment]
Just updated it guys 👍, let me know if the problem subsides
