### ISSUE TITLE
Help with Errors

### ISSUE THREAD

**Issue by totoZB** [nickpettican/InstaBot#3]
Hello,

I just did a clean git clone but i'm getting some errors : 

```
Trying to sign in as yyyyyyyyyyy...  successfully signed in!

**ERROR getting user data.**

Starting operations - 16:20:34 09/03/2017

Current daily count:
 - All operations: 322
 - Like news feed: 9
 - Likes: 255
 - Follows: 29
 - Unfollows: 29
 - Comments: 0

Refilling bucket - looking for "xxxxxxxxxxxxx" posts...

Scrowling through feed for friend's posts...

**ERROR getting news feed media.
Checking the profiles of those you follow...
Error: 'bool' object is not iterable**

Current daily count:
 - All operations: 322
 - Like news feed: 9
 - Likes: 255
 - Follows: 29
 - Unfollows: 29
 - Comments: 0
```

Do you have any idea how i can debug these ? Thanks !

**Comment by nickpettican** [comment]
Hi @totoZB, thanks for the feedback.

This is because Instagram has recently changed it's backend a bit. I just fixed it up, so just download the newest version `1.0.3` and it should work.

**Comment by nickpettican** [comment]
No worries!

That will be a *ZeroDivisionError* in `instafunctions.py`, I just pushed a new version where this error should be fixed :). Let me know if the problem continues!

Best

**Comment by totoZB** [comment]
Thanks everything working fine now :)
