### ISSUE TITLE
Please add location support

### ISSUE THREAD

**Issue by farid-st** [nickpettican/InstaBot#31]
Would be great to have this feature, thank you very much! And also don't know why but it starts to like posts that don't have hashtags that are not in tags.csv

Thank you!

**Comment by nickpettican** [comment]
Hi @farid-st thanks for the feedback. I will try and find the time to do this, I'm currently transitioning country so I'm pretty busy 😓.
In terms of the posts that don't have the hashtag, that's instagram's doing - they use machine learning to figure out where some posts belong depending on their caption even if they didn't include the hashtag.

**Comment by nickpettican** [comment]
I realised that when I was building the bot I tried to implement this but found that location was not available. Sorry about that. If you find out that it is possible feel free to reopen this issue 👍
