### ISSUE TITLE
 Willing to Contribute Great Content to the Instabot 1.2 Site Homepage 

### ISSUE THREAD

**Issue by order4adwriter** [nickpettican/InstaBot#35]
Hi,

My name is Phil and I am a professional copywriter.

I'd like to contribute to the instabot 1.2 project by creating informative, compelling and enticing content for the website homepage.

I have done this for many other projects here on GitHub and I believe my copywriting contributions will be immensely beneficial to the Instabot 1.2 project.

In this vein, I'll also be submitting other contributions for the website such as ...
Homepage content
FAQ page content
About Instabot
Wiki content
Press releases/ blog posts
Tutorials on How to use Instabot effectively

...and other content as required by the POs.

Such content will undoubtedly improve return traffic to the website and ultimately convince more site visitors to download and install the app, thereby increasing the popularity of the app in the long run.

Now...

Can I go ahead and create the content?

Also, will the contributions be merged to the master repository?

Please let me know asap, so I could get started immediately.

I know that I probably don't need to do this but I believe that getting your permission before going ahead is indeed the right thing to do.

Thanks for taking the time to read this as I readily await your positive response.

**Comment by order4adwriter** [comment]
please respond asap

**Comment by nickpettican** [comment]
Sorry @order4adwriter I'm not sure what you mean. This project is a python script that automates your Instagram activity, and the README explains how to use it in a detail. It doesn't have/need a website.
Thanks for the offer though :)
