### ISSUE TITLE
Cant install requirements 

### ISSUE THREAD

**Issue by 5p4ce** [nickpettican/InstaBot#39]
always get that error:

pip install -r requirements.txt
Collecting arrow (from -r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/arrow/arrow-0.12.1-py2.py3-none-any.whl
Collecting requests (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting time (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement time (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for time (from -r requirements.txt (line 3))

**Comment by nickpettican** [comment]
Remove `time` from the requirements file, I don't know why it is there, it doesn't need to be pip installed.
