### ISSUE TITLE
Trying to sign in

### ISSUE THREAD

**Issue by 5p4ce** [nickpettican/InstaBot#40]
dosent work, always get that error:

ERROR while attempting sign in: "name='csrftoken', domain=None, path=None"

**Comment by nickpettican** [comment]
Hi @5p4ce thanks for the feedback. It appears Instagram have changed their backend so I'll have to update the login function. I'll let you know when it's fixed.

**Comment by LopesX** [comment]
Hey Friends, i use this instabot and works fine:
https://github.com/instabot-py/instabot.py

@nickpettican can fix your instbot reading it?

**Comment by LopesX** [comment]
@nickpettican You learn python on free course ? i want learning more to help us

**Comment by nickpettican** [comment]
The login issue is fixed, yet sometimes you may get the `checkpoint error`. If you do, just follow this https://www.gramto.com/article/how-to-bypass-instagram-checkpoint/

**Comment by nickpettican** [comment]
@LopesX I learned through online course at first, and then by profession and side projects. I highly encourage you to keep going :)
