### ISSUE TITLE
Some Errors ... 

### ISSUE THREAD

**Issue by ar8001** [nickpettican/InstaBot#41]
sudo pip install -r requirements.txt
Collecting arrow (from -r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/arrow/arrow-0.12.1-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Collecting time (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement time (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for time (from -r requirements.txt (line 3))

and the next one: 

python run.py 
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from src.instabot import InstaBot
  File "/home/pi/instagrambot/InstaBot/src/instabot.py", line 23, in <module>
    import arrow
ImportError: No module named arrow

**Comment by nickpettican** [comment]
Arrow has now been removed from the dependency list :)
