### ISSUE TITLE
Error when linking friends posts

### ISSUE THREAD

**Issue by jrgoode** [nickpettican/InstaBot#43]
Hey there! I set up the bot and am able to have it run all the commands with the exception of it liking my friend's posts (which is the main feature I'm looking to use). 

This is the error I'm receiving: 

Scrolling through feed for friend's posts:  
Error getting new feed data: 'graphql'.
Error: object of type 'bool' has no len()

Is this a bug or something I haven't installed or set up correctly?

**Comment by nickpettican** [comment]
Fixed in the next update of version 1.3.0 :)
Instagram had modified the news feed data, but now Instabot can like friends posts again
