### ISSUE TITLE
Unfollow: False not working

### ISSUE THREAD

**Issue by jrgoode** [nickpettican/InstaBot#45]
Hey there. I'm trying to use your app just to like posts from people my instagram account is following. 

I set the unfollow variable to false, however the first command that it runs after starting it up is to unfollow users. Is there something I didn't configure correctly? 

Thanks!

**Comment by nickpettican** [comment]
Hi @jrgoode, thanks for the feedback. Could you provide me with the logs? I'm unsure as to what this could be... if you haven't followed any users then it shouldn't be unfollowing.

**Comment by jrgoode** [comment]
Thanks for responding! Before I saw this I did a fresh build and I'm no longer getting the same issue as before, however now when I run I'm getting an error that the list index is out of range. 

Something I'm not doing correctly?

[activity_log_23-11-2018.txt](https://github.com/nickpettican/InstaBot/files/2613501/activity_log_23-11-2018.txt)

**Comment by nickpettican** [comment]
Hi @jrgoode thanks for that. I'll look into it. To help me out could you comment out lines 755 and 756 in `src/instabot.py` like this?
```Python
#            except Exception as e:
#                self.logger.log('Error: %s' % (e))
```
And then send me the logs for what you get?
This way we can get a full error stack to see where it originates.

**Comment by jrgoode** [comment]
Done. Thank you very much for your help!

[activity_log_29-11-2018.txt](https://github.com/nickpettican/InstaBot/files/2631140/activity_log_29-11-2018.txt)

**Comment by jrgoode** [comment]
How can I get that to you? Sorry, noob here :)

**Comment by nickpettican** [comment]
@jrgoode no worries :). Download the newest version - I've included more detailed error logging, so after you get the error send me the stacktrace or log file and I'll see what I can do

**Comment by jrgoode** [comment]
That seemed to do it! Working quite well now, thank you very much! 11/10 support 😄
