### ISSUE TITLE
ERROR while attempting sign in: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by miguellazaro** [nickpettican/InstaBot#47]
Hi,
suddenly this error appears at login:

Trying to sign in as xxxxxxxxxxxx:
ERROR while attempting sign in: "name='csrftoken', domain=None, path=None"

Thanks so much.

**Comment by nickpettican** [comment]
Hi @miguellazaro, make sure you included the right username and password. I've updated InstaBot to log bugs with more detail - download the newest version and if this problem continues add the log file here with the full error stack and I'll see what I can do :)

**Comment by TMlucas** [comment]
Hi, today I got the same error when I relaunched the bot (it worked great before). 
So I did the update but the error stay. I think the program can't get the cookie to sign in.
![image](https://user-images.githubusercontent.com/33508417/49461239-7feaad80-f7f3-11e8-9d05-8619f36ae916.png)
I hope you'll find the mistakes.
Thanks for your work

**Comment by TMlucas** [comment]
It works!
Thanks a lot

**Comment by miguellazaro** [comment]
Fixed. Thanks so much.
