### ISSUE TITLE
Error while logging: Invalid format string

### ISSUE THREAD

**Issue by izhzz** [nickpettican/InstaBot#49]
I get this message after I start it. I run it on Windows Server 2016 64-bit and Python 2.7. Was using a similar InstaBot before but it stopped working.

Log:
Error while logging: Invalid format string
Success

        Starting Bot at 14:12 2018-12-10

        Current daily count:
         - All operations: 307
         - Like news feed: 0
         - Likes: 253
         - Follows: 27
         - Unfollows: 27
         - Comments: 0

Error while logging: Invalid format string
found 64 new.

Error while logging: Invalid format string
Error: object of type 'bool' has no len()
Traceback (most recent call last):
  File "C:\InstaBot-master\src\instabot.py", line 735, in main
    self.main_loop()
  File "C:\InstaBot-master\src\instabot.py", line 782, in main_loop
    self.refill_bucket()
  File "C:\InstaBot-master\src\instabot.py", line 899, in refill_bucket
    (len(feed_data), len(
TypeError: object of type 'bool' has no len()

        Current daily count:
         - All operations: 307
         - Like news feed: 0
         - Likes: 253
         - Follows: 27
         - Unfollows: 27
         - Comments: 0

Error while logging: Invalid format string
Success

        --- Delaying 9.20300006866 seconds ---

Error while logging: Invalid format string
Success

        --- Delaying 71.3900001049 seconds ---

**Comment by nickpettican** [comment]
Hi @izhzz thanks for the feedback. The issue was with datetime string parsing on windows. It should be fixed now :). Let me know so I can close the issue.

**Comment by izhzz** [comment]
> Let me know so I can close the issue.
Wow, great! Everything works now :D
