### ISSUE TITLE
looping over checkpoint required

### ISSUE THREAD

**Issue by vladgrish** [nickpettican/InstaBot#52]
[ 2018-12-26 16:12:23 ] Trying to sign in as <username>: [ 2018-12-26 16:12:29 ] Error signing in.Request returns 400 error.
Instagram error message: checkpoint_required
Checkpoint_url: /challenge/yyy/xxx/
Open Instagram on your desktop browser and confirm that it is you trying to log in!

reoccurring after refreshing the browser and passing the test

**Comment by nickpettican** [comment]
This may happen sometimes. Once you have passed the test just wait a few hours and it should work.
