### ISSUE TITLE
Error on start ImportError: No module named requests

### ISSUE THREAD

**Issue by phorest0** [nickpettican/InstaBot#54]
Hi, I've got this on start:

`InstaBot-master me$ python run.py

Traceback (most recent call last):

  File "run.py", line 23, in <module>
    from src.instabot import InstaBot
  File "/Users/me/InstaBot-master/src/instabot.py", line 26, in <module>
    from requests import Session

ImportError: No module named requests`

Please help

**Comment by nickpettican** [comment]
Hi @phorest0, you have to run `pip install -r requirements.txt` to install the required library, in this case requests

**Comment by phorest0** [comment]
Right after restarting I've got this:
![image](https://user-images.githubusercontent.com/20317093/52163307-e4899200-26e8-11e9-80c3-39d14d4772ce.png)

<img width="829" alt="screen shot 2019-02-02 at 12 42 13" src="https://user-images.githubusercontent.com/20317093/52163289-a7250480-26e8-11e9-8191-97d8e9178c40.png">

then I've put  Python in this folder and now i've got this


<img width="522" alt="screen shot 2019-02-02 at 12 51 24" src="https://user-images.githubusercontent.com/20317093/52163344-4944ec80-26e9-11e9-8e59-03bb94f38cf9.png">

**Comment by phorest0** [comment]
Ok, Never mind! I've tried to put different python files to this folder: "/usr/local/bin/" and the magic come back! Anyway, Thanks for helping mate!
<img width="527" alt="screen shot 2019-02-02 at 13 06 54" src="https://user-images.githubusercontent.com/20317093/52163521-d25d2300-26eb-11e9-8763-9706a7f980c0.png">

**Comment by nickpettican** [comment]
It can get a bit messy to have different versions of python 😅. I recommend using [conda](https://conda.io/en/latest/miniconda.html) to manage python versions and environments. Let me know if you get it sorted 👍

**Comment by nickpettican** [comment]
Closing this, as I assume it works now :)
