### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Stevio2000** [nickpettican/InstaBot#55]
# python run.py                                                                 
  File "run.py", line 35                                                        
    print 'Could not open config file, check parameters.'                       
                                                        ^                       
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Could n
ot open config file, check parameters.')?

**Comment by nickpettican** [comment]
Hi @Stevio2000 , you're probably using Python 3, you need Python 2 to run the bot. I recommend using [conda](https://conda.io/en/latest/miniconda.html) to manage python versions and environments. Let me know if you get it sorted 👍

**Comment by nickpettican** [comment]
Closing this, let me know if it's still not working and I can reopen
