### ISSUE TITLE
How to add comments

### ISSUE THREAD

**Issue by itwt490** [nickpettican/InstaBot#6]
I followed the code but I don't see how to set up comments? (only how to set number of comment per day)

**Comment by nickpettican** [comment]
Hi @itwt490 
The comments generator is here: https://github.com/nickpettican/InstaBot/blob/master/src/instafunctions.py#L191
There are currently three lists out of which one element will be randomly picked from each one to create the comment. You can add extra lists if you want to extend the sentence. For the emojis I used http://getemoji.com/, just copy and paste the one you want into the list.
Let me know if you have any trouble.
